### ISSUE TITLE
aff3ct_at_wrong_place!

### ISSUE THREAD

**Issue by kumuds4** [aff3ct/error_rate_references#2]
attached!
[aff3ct.exe_wrong button_needhelp!.pdf](https://github.com/aff3ct/error_rate_references/files/1817790/aff3ct.exe_wrong.button_needhelp.pdf)

**Comment by kouchy** [comment]
Dear @kumuds4,

We cannot make full software support of an Open-source project.
Your question is not well explained and I think this not related to this repo.

Thanks.
